### ISSUE TITLE
🐛 fix: eqc transpiles every configuration's generated sources, so a Release build binds a Debug factory

### ISSUE THREAD

**Issue by edgarmesquita** [eQuantic/equantic-ui#244]
Reported by the visual parity review session on the site (.54), and reproduced here on 0.2.0-preview.55 with a fresh `dotnet new equantic-app` from nuget.org.

The recipe, in the template app:

1. `dotnet build -c Debug`, which writes `obj/Debug/net10.0/generated/…/AppFactorySurfaceGenerator/AppUI.g.cs` with the `StatTile` factory
2. delete `Components/StatTile.cs` and its uses
3. `dotnet build -c Release`

The C# compile passes and eqc fails:

```
obj/Debug/net10.0/generated/…/AppUI.g.cs(11,95): error EQ2006: 'StatTile' does not bind …
obj/Release/net10.0//generated/…/AppUI.g.cs(11,95): error EQ2006: 'StatTile' does not bind …
obj/Release/net10.0/generated/…/AppUI.g.cs(11,95): error EQ2006: 'StatTile' does not bind …
```

Three files for one type, and the SDK DID pass `--generated "<project>/obj/Release/net10.0//generated"`. The first is the other configuration's stale factory, which is what the site hit twice: EQ2006 accusing a deleted `WrapRow`, and EQ1006 saying `AppUI` is declared in more than one place while a Debug dev server and a Release build shared the project. The last two are the SAME file, reached once through `--generated` (the double slash comes from the .NET SDK's own default, `$(IntermediateOutputPath)/generated`) and once by walking the directory.

Why `--generated` does not scope it: the semantic model is built right. `src/eQuantic.Build/Program.cs:64` uses `GetProjectSourceFiles`, which excludes `obj/` and `bin/`, and adds the `--generated` files. The list of MODULES to transpile is built separately, at `Program.cs:339-341`, with a raw `Directory.GetFiles(dir, "*.cs", SearchOption.AllDirectories)` over the project directory. The loop at `Program.cs:354` then skips `obj/` and `bin/`... unless the path contains `/generated/`, an exemption meant to let the `--generated` files through. It is decided by the SHAPE of the path rather than by where the file came from, so every configuration's `obj/*/…/generated/` walks straight past it.

It is two pieces answering "which files are this project's sources" each by itself, and the cure is one function with two callers: build the module list from `GetProjectSourceFiles` plus the `--generated` files, tagged as such, drop the path-shape exemption, and normalize with `Path.GetFullPath` so one file cannot arrive under two spellings.

Worth a pin that fails on today's code: a project directory holding `obj/Debug/…/generated/X.g.cs` and `obj/Release/…/generated/X.g.cs` with different content, `--generated` pointing at Release, and the module list asserted to hold the Release file exactly once.

One more thing measured along the way, smaller and not eqc's to fix alone: a generated file the generator STOPS emitting stays on disk in the current configuration too. Deleting the app's last component left `obj/Release/…/AppUI.g.cs` (written 21:28) in place through the next Release build (21:31), still naming `StatTile`. After the fix above that case survives only when a generator emits nothing at all for a file, but it deserves a look at whether the SDK should prune `$(CompilerGeneratedFilesOutputPath)` before the compile, measured against incremental builds that skip `CoreCompile`.

**Comment by edgarmesquita** [comment]
Corrected by #250, which went in without a closing keyword, so I'm closing this by hand.

I ran the recipe from this issue on a fresh template from nuget.org: a Debug build, the component deleted, then a Release build. With the .55 eqc it still fails with EQ2006 on `StatTile`, and with main's eqc it builds.

Two things are left over, and they have their own issue, #253, so they don't live only in a closed one: the new pin exercises `GetCompilationUnits` and not eqc's own `Program.cs`, where the defect was, and a generated file its generator stops emitting still survives in the configuration being built.
