### PR TITLE
🐛 fix: the build tools are edges of the build graph, not inline builds

### PR DESCRIPTION
**Pull request by edgarmesquita**
## What broke

A cold `dotnet build` of the solution — a fresh clone, or a tree without `bin/`/`obj/` — failed and passed on the second run:

- `error CS0103: The name 'Vectors' does not exist` in `DefaultUIDashboard`
- five `error XA2001: Source file '…/mipmap-*/ic_launcher.png' could not be found` in `WalletMobile`

Reported by a consumer building the tree cold, reproduced here on `main` at 2d3dbc2a: **6 errors cold, 0 warm**, with all eight test suites green and every sample green when built on its own. Nothing the CI runs sees it — the CI builds project by project.

## Why

`eqc` and `eqicon` were built by inline `<MSBuild Targets="Restore;Build" Properties="Configuration=…">` tasks — in the web `Sdk.targets`, in the Android InitialTarget, and in both pack projects. Each is a **second instance** of the tool's project under its own global properties, racing the solution's own build of the same project into the same `bin/`. Every target that ran a tool was guarded by `Exists(eqicon.dll)`, which answered "no" the first time and skipped in silence; the error surfaced two targets later, about a symbol or a PNG. It passed for months by the accident of where the projects sat in the `.sln`.

## What changes

- **The tools are edges of the build graph.** Both `Sdk.props` declare `eQuantic.Build` / `eQuantic.UI.Native.Build` as `ProjectReference` with `ReferenceOutputAssembly=false`. MSBuild orders and serializes them; there is one instance. `Private=false`, because an exe's apphost, `deps.json` and `runtimeconfig.json` were riding `GetCopyToOutputDirectoryItems` into every sample's `bin/` and into the iOS bundle (four `PublishFolderType` warnings). `GlobalPropertiesToRemove` for framework/runtime/publish properties, because a `net10.0;net10.0-ios;net10.0-android` head must not hand a plain `net10.0` tool its own framework (`UndefineProperties` alone gave NETSDK1047).
- **The Android InitialTarget pulls that one edge itself.** An InitialTarget runs before `ResolveProjectReferences`, so it calls the edge with `RemoveProperties="%(ProjectReference.GlobalPropertiesToRemove)"` — the same instance the solution builds — and does nothing during restore (`ExcludeRestorePackageImports`, NuGet's own marker) or a design-time build.
- **Where the tool is found is one question.** `_EqSourceTree` decides `EqcCliPath` and `_EqIconToolDir` at evaluation in both SDKs: a source tree runs what its edges just built, a package runs what it shipped under `tools/`. Three `Exists`-fallback chains and the `EQuanticToolsFromSource` target go. So do the post-build copies into `<Sdk>/tools/`, which nothing has read since `_EqSourceTree` existed — the stale copy they left is what made my first A/B of this fix pass for the wrong reason (the icons were generated three seconds *before* the `bin/`'s `eqicon.dll` existed).
- **The pack projects collect, they do not build.** `eQuantic.UI.Sdk.csproj` and `eQuantic.UI.Sdk.Native.csproj` reference the tools the same way (`PrivateAssets=All`, so the packages gain no dependency); `CollectBuildOutput`/`CollectIconTool` only gather the files. The `Restore;Build` the inline task needed for a clean CI checkout is what a graph restore does by construction.
- **Fail loud, once.** `EQuanticRequireIconTool` (EQ4001) runs before every consumer of the tool in both SDKs; the seven `Exists(eqicon.dll)` conditions on the consumers are gone. A missing tool is a broken tree or a broken package, and now says so.
- **Android launcher resources only when there is an AppIcon.** A literal `AndroidResource` path to a file nothing writes was five XA2001s for an app without an icon.
- **The Debug auto-pack never ran.** `AutoPackAfterBuild` compared `IsPackableProject` to `'true'` and the value carried its own indentation (`"\n            true"`) since 4a52258b (January): not one execution, no `1.0.0-dev` package ever. Removed, with the two docs that promised it.

## Evidence (this tree, macOS, .NET SDK 10.0.301)

| check | result |
|---|---|
| solution, every `bin/`/`obj/` removed | 0 errors; `tools/` not recreated; 0 eqicon files in sample bins; 5 mipmap dirs generated |
| solution, cold tools + samples, second sample | 0 errors |
| each sample alone from cold (project build, not solution) | 0 errors × 3 |
| A/B: web edges removed | **EQ4001 by name** (was CS0103 `Vectors`) |
| A/B: Android pull removed | **EQ4001 by name** (was XA2001 × 5) |
| Android app without `AppIcon.png` | 0 errors (old condition, measured: XA2001 × 5) |
| `dotnet test` | 8 suites, 4090 passed, 0 failed, 1 skipped |
| `dotnet pack` of both SDKs, Release, from cold — the CI path | 0 errors; Sdk carries `eqc.dll` + `eqicon.dll`, Sdk.Native `eqicon.dll`; nuspec dependencies: none |
| MSB/NU/NETSDK warnings in the cold solution build | none |

## Left alone, on purpose

- `.gitignore` keeps `src/eQuantic.UI.Sdk*/tools/`: clones older than this PR still have the folder, and nothing reads it now.
- `docs/COMPILE-TIME-EVALUATION-INDEX.md` still shows `dotnet pack src/eQuantic.UI.Core …` — Core is gone since #83; that is a docs sweep, not this PR.
- CI is unaffected: it builds and packs project by project, and `dotnet pack` of the SDKs now builds the tools through the edge instead of the inline task.

### CODE REVIEW

File: src/eQuantic.UI.Sdk/Sdk/Sdk.targets [hunk 1]
```diff
@@ -1,44 +1,23 @@
...
-    <PropertyGroup Condition="Exists('$(MSBuildThisFileDirectory)../../eQuantic.Build/eQuantic.Build.csproj')">
-        <_EqSourceTree>true</_EqSourceTree>
+    <PropertyGroup>
+        <_SdkToolsDir>$(MSBuildThisFileDirectory)../tools/net10.0/</_SdkToolsDir>
+        <_EqSourceTree Condition="Exists('$(MSBuildThisFileDirectory)../../eQuantic.Build/eQuantic.Build.csproj')">true</_EqSourceTree>
+        <EqcCliPath Condition="'$(EqcCliPath)' == '' AND '$(_EqSourceTree)' == 'true'">$(MSBuildThisFileDirectory)../../eQuantic.Build/bin/$(Configuration)/net10.0/eqc.dll</EqcCliPath>
+        <EqcCliPath Condition="'$(EqcCliPath)' == ''">$(_SdkToolsDir)eqc.dll</EqcCliPath>
+        <_EqIconToolDir Condition="'$(_EqSourceTree)' == 'true'">$(MSBuildThisFileDirectory)../../eQuantic.UI.Native.Build/bin/$(Configuration)/net10.0/</_EqIconToolDir>
+        <_EqIconToolDir Condition="'$(_EqIconToolDir)' == ''">$(_SdkToolsDir)</_EqIconToolDir>
     </PropertyGroup>
```
[the remark this answers is not in the document]
Comment (edgarmesquita) [reply src/eQuantic.UI.Sdk/Sdk/Sdk.targets:20]: Right — and what WarnNoCli guarded was worse than the guard: CompileEQuanticUI skipped in silence and the build shipped a page with no JavaScript behind a warning. Replaced by EQuanticRequireCompiler (EQ4002), which fails before CompileEQuanticUI when the file is not there — source tree, package, or an explicit EqcCliPath — and CompileEQuanticUI no longer conditions on the path being set. Measured: `-p:EqcCliPath=/nope/eqc.dll` on the dashboard sample fails with EQ4002 by name; the normal build still emits its JavaScript. EQ4002 has its row in docs/DIAGNOSTICS.md and the guard's baseline.

File: src/eQuantic.UI.Sdk/Sdk/Sdk.targets [hunk 2]
```diff
@@ -357,8 +333,22 @@
...
+        Condition, so a missing tool meant no Vectors.g.cs and a CS0103 on `Vectors` two targets
+        later — an error about a symbol, for a cause about a tool, on a cold build only. With the
+        tool declared as a graph edge it is present in dev mode by construction, and present in
+        package mode because the SDK ships it under tools/; the only way to get here without it is a
+        broken package or a broken tree, and that deserves its own name.
+    -->
+    <Target Name="EQuanticRequireIconTool" BeforeTargets="EQuanticVectors;EQuanticWebAppIcon"
+        Condition="(Exists('$(EQuanticAssetsDir)') OR '$(EQuanticAppIconSource)' != '') AND !Exists('$(_EqIconToolDir)eqicon.dll')">
+        <Error Code="EQ4001"
+            Text="This project has assets to generate from ($(EQuanticAssetsDir)) but the eQuantic icon tool is missing at '$(_EqIconToolDir)eqicon.dll'. In a source-tree build this is a broken build graph (eQuantic.UI.Native.Build did not build first); from a package it is a broken SDK package. Neither is fixed by building twice." />
```
[the remark this answers is not in the document]
Comment (edgarmesquita) [reply src/eQuantic.UI.Sdk/Sdk/Sdk.targets]: Reworded: the message now names both things the target generates — the vector catalog from EQuanticAssetsDir and the app icon from EQuanticAppIconSource — since either alone triggers it.
